developement:
  username: "fq2yyg9IVcaI"
  password: "H5PyWERV8kfh"
  politiki_uri: "http://localhost:3000/api/"
  amqp_host: mq.politiki.si
  twitter_consumer_key: ccxOTpcD9rgaUkWrwEdGrA
  twitter_consumer_secret: 8Bem97vcdSa2AXCv8Gs28LtgJ7FXUdu8WAtWS2PE9c
  twitter_access_token: 20590206-Ka9X824CS4UfwAr6FOKMK7CCdoQikuUEwV1b9HHNQ
  twitter_access_token_secret: F6N2r41nBj791vHMkUO6nsrpEWUmk5pK4SGsSK2nyo
  log_path: 0
  facebook_key: "349572658447641"
  facebook_secret: "7f075733a50df7955c9e357f6310212b"
  facebook_token: AAAE97zohRRkBAPcyn9KIDdHn4ELgaUWcUVgZAEUbxtkQHd1HU1HlTuZBFddvK43NhzvG3N27Nx0i6dusqsB2ZABoRuTRsupgSmaluf8jQZDZD

production:
  username: "fq2yyg9IVcaI"
  password: "H5PyWERV8kfh"
  politiki_uri: "http://localhost:3000/api/"
  amqp_host: mq.politiki.si
  twitter_consumer_key: ccxOTpcD9rgaUkWrwEdGrA
  twitter_consumer_secret: 8Bem97vcdSa2AXCv8Gs28LtgJ7FXUdu8WAtWS2PE9c
  twitter_access_token: 20590206-Ka9X824CS4UfwAr6FOKMK7CCdoQikuUEwV1b9HHNQ
  twitter_access_token_secret: F6N2r41nBj791vHMkUO6nsrpEWUmk5pK4SGsSK2nyo
  log_path: '/dev/null'
  facebook_key: "349572658447641"
  facebook_secret: "7f075733a50df7955c9e357f6310212b"
  facebook_token: AAAE97zohRRkBAPcyn9KIDdHn4ELgaUWcUVgZAEUbxtkQHd1HU1HlTuZBFddvK43NhzvG3N27Nx0i6dusqsB2ZABoRuTRsupgSmaluf8jQZDZD
  